
spring:
  datasource:
    username: root
    password: 556677
    # url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    url: jdbc:mysql://localhost:3306/xm1?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8086
mybatis:
  type-aliases-package: cn.nn.domain
